name: Build SG Jobs

on:
  workflow_dispatch:
  push:
    branches: [ main, feature/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install npm dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Install composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Pack plugin artifact
        run: |
          mkdir -p artifact
          zip -r artifact/sg-jobs-build.zip sg-jobs.php vendor dist src public

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sg-jobs
          path: artifact/sg-jobs-build.zip
